name: platform-test

on:
  push:
    branches:
      - main
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven test
        run: mvn -B clean test
